// <auto-generated />
using System;
using GraphQL.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Web.GraphQL.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20220815061731_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GraphQL.Model.Entity.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72d95bfd-1dac-4bc2-adc1-f28fd43777fd"),
                            Name = "Superman and Lois",
                            Price = 0
                        },
                        new
                        {
                            Id = new Guid("c32cc263-a7af-4fbd-99a0-aceb57c91f6b"),
                            Name = "Game of Thrones",
                            Price = 0
                        },
                        new
                        {
                            Id = new Guid("7b6bf2e3-5d91-4e75-b62f-7357079acc51"),
                            Name = "Avengers: Endgame",
                            Price = 0
                        });
                });

            modelBuilder.Entity("GraphQL.Model.Entity.Movie", b =>
                {
                    b.OwnsMany("GraphQL.Model.Entity.Review", "Reviews", b1 =>
                        {
                            b1.Property<Guid>("MovieId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<string>("Reviewer")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Stars")
                                .HasColumnType("int");

                            b1.HasKey("MovieId", "Id");

                            b1.ToTable("Review");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");

                            b1.HasData(
                                new
                                {
                                    MovieId = new Guid("72d95bfd-1dac-4bc2-adc1-f28fd43777fd"),
                                    Id = 1,
                                    Reviewer = "A",
                                    Stars = 4
                                },
                                new
                                {
                                    MovieId = new Guid("72d95bfd-1dac-4bc2-adc1-f28fd43777fd"),
                                    Id = 2,
                                    Reviewer = "B",
                                    Stars = 5
                                },
                                new
                                {
                                    MovieId = new Guid("c32cc263-a7af-4fbd-99a0-aceb57c91f6b"),
                                    Id = 3,
                                    Reviewer = "A",
                                    Stars = 4
                                },
                                new
                                {
                                    MovieId = new Guid("c32cc263-a7af-4fbd-99a0-aceb57c91f6b"),
                                    Id = 4,
                                    Reviewer = "D",
                                    Stars = 5
                                },
                                new
                                {
                                    MovieId = new Guid("c32cc263-a7af-4fbd-99a0-aceb57c91f6b"),
                                    Id = 5,
                                    Reviewer = "E",
                                    Stars = 3
                                },
                                new
                                {
                                    MovieId = new Guid("c32cc263-a7af-4fbd-99a0-aceb57c91f6b"),
                                    Id = 6,
                                    Reviewer = "F",
                                    Stars = 5
                                },
                                new
                                {
                                    MovieId = new Guid("7b6bf2e3-5d91-4e75-b62f-7357079acc51"),
                                    Id = 7,
                                    Reviewer = "A",
                                    Stars = 2
                                },
                                new
                                {
                                    MovieId = new Guid("7b6bf2e3-5d91-4e75-b62f-7357079acc51"),
                                    Id = 8,
                                    Reviewer = "B",
                                    Stars = 1
                                },
                                new
                                {
                                    MovieId = new Guid("7b6bf2e3-5d91-4e75-b62f-7357079acc51"),
                                    Id = 9,
                                    Reviewer = "G",
                                    Stars = 3
                                },
                                new
                                {
                                    MovieId = new Guid("7b6bf2e3-5d91-4e75-b62f-7357079acc51"),
                                    Id = 10,
                                    Reviewer = "H",
                                    Stars = 4
                                });
                        });

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
